name: lab3 CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ["1.18.4"]
        otp: ["26.2"]
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
            ~/.mix
            ~/.cache/dialyzer
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Get deps
        run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      - name: Compile
        run: MIX_ENV=test mix compile

      - name: Credo
        run: mix credo --strict

      - name: Run tests
        run: mix test --trace --color
